#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

StartString='->  PRE-COMMIT HOOK STARTING...'
FinishString='\n->  PRE-COMMIT HOOK CHECKS FINISHED\n'

echo "$StartString"
npx --no -- commitlint --edit
npm run prettier:write
echo "$FinishString"
