#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

StartString='->  PRE-COMMIT HOOK STARTING...\n'
FinishString='->  PRE-COMMIT HOOK CHECKS FINISHED\n'

echo "$StartString"
npx --no -- commitlint --edit
echo "$FinishString"
