#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

startString='->  PRE-PUSH HOOK STARTING...'
finishString='\n->  PRE-PUSH HOOK CHECKS SUCCESSFULLY FINISHED\n'

echo "$startString"

echo "$finishString"
